//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Laolu at BLUECHIP-PC on 06/10/2017 20:11:10 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace TECi.Entities
{
    /// <summary>
    /// Represents a row of CourseCategory data.
    /// </summary>
    [DataContract]
    public partial class CourseCategoryold
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Category_Name column.
        /// </summary>
        [DataMember]
        public string Category_Name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Category_Desc column.
        /// </summary>
        [DataMember]
        public string Category_Desc { get; set; }

        /// <summary>
        /// Gets or sets a string value for the IdNumber column.
        /// </summary>
        [DataMember]
        public string IdNumber { get; set; }

        /// <summary>
        /// Gets or sets a int value for the parent column.
        /// </summary>
        [DataMember]
        public int parent { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the enabled column.
        /// </summary>
        [DataMember]
        public bool enabled { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the created_date column.
        /// </summary>
        [DataMember]
        public DateTime? created_date { get; set; }

        /// <summary>
        /// Gets or sets a string value for the created_by column.
        /// </summary>
        [DataMember]
        public string created_by { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the modified_date column.
        /// </summary>
        [DataMember]
        public DateTime? modified_date { get; set; }

        /// <summary>
        /// Gets or sets a string value for the modified_by column.
        /// </summary>
        [DataMember]
        public string modified_by { get; set; }
    }
}
